server:
  port: 10010
spring:
  application:
    name: Gateway #网关服务的名称
  cloud:
    nacos:
      server-addr: localhost:8848 #配置nacos服务地址
    gateway:
      routes: #配置路由
        - id: user-service #路由的唯一id
          uri: lb://userService #lb负载均衡，服务在nacos中的地址
          predicates:
            - Path=/user/** #路由断言，请求路径满足这个的会去被分配去访问这个路由
      globalcors:  #解决跨域问题
        add-to-simple-url-handler-mapping: true   #允许浏览器的options访问行为
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"    #允许那些网址进行跨域请求
            allowedMethods: #允许进行跨域的方法
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" #允许的请求头，所有请求头
            allowCredentials: true #允许请求携带cookies
            maxAge: 360000 #这次跨域请求的有效期


  datasource: #配置数据库
    druid:
      url: jdbc:mysql://localhost:3306/zhibo
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
