server:
  port: 8083
spring:
  application:
    name: liveroomservice #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务注册地址
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://175.178.85.36:3306/zhibo
  #配置redis
  redis:
    database: 0 #使用0号数据库
    host: 175.178.85.36
    port: 6379
    jedis:
      pool:
        max-idle: 4 #最大空闲连接数
        max-active: 8 #最大连接数
        min-idle: 0 #最小空闲连接数
        max-wait: 1ms #数据库最大阻塞时间
#配置mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id #使用雪花算法生成id
      logic-delete-value: 1 #逻辑删除赋值1
      logic-not-delete-value: 0 #未删除的是0
  configuration:
    map-underscore-to-camel-case: true  #驼峰映射下划线
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #控制台打印sql信息
