server:
  port: 8082
spring:
  application:
    name: userservice #服务名称
  cloud:
    nacos:
      server-addr: 139.159.136.22:8848 #nacos服务地址
#      discovery:
#        ip: 116.205.128.182
#        port: 8082
  datasource: #配置数据库
    druid:
      url: jdbc:mysql://139.159.136.22:3306/zhibo
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 852456jkl
  #配置redis
  redis:
    database: 0 #使用0号数据库
    password: 123456
    host: 139.159.136.22
    port: 6379
    jedis:
      pool:
        max-idle: 4 #最大空闲连接数
        max-active: 8 #最大连接数
        min-idle: 0 #最小空闲连接数
        max-wait: 1ms #数据库最大阻塞时间
 #配置rabbitmq
  rabbitmq:
    addresses: 139.159.136.22
    username: yue
    password: yue
    virtual-host: /
#配置mybatisPlus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #启用驼峰合下划线之间的映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出sql语句
  global-config: #数据库表全局id生成策略
    db-config:
      id-type: assign_id #使用雪花算法生成id

