server:
  port: 8087
spring:
  application:
    name: searchservice #服务名称
  cloud:
    nacos:
      server-addr: 139.159.136.22:8848 #nacos服务注册地址
#      discovery:
#        ip: 121.37.24.27
#        port: 8087
      #配置数据库
  datasource:
    druid:
      url: jdbc:mysql//localhost:3306?zhibo
      username: root
      password: 852456jkl
      driver-class-name: com.mysql.cj.jdbc.Driver
  #配置redis
  redis:
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #超时时间
        min-idle: 0 #最小空闲连接池数
        max-idle: 4 #最大空闲连接数
    database: 0
    password: 123456
    host: 139.159.136.22
    port: 6379
  #配置rabbitmq
  rabbitmq:
    addresses: 139.159.136.22
    username: yue
    password: yue
    virtual-host: /
#配置mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id #使用雪花算法生成id
      logic-not-delete-value: 0 #逻辑删除，未删除的值
      logic-delete-value: 1 #逻辑删除，删除时显示的值
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输入mysql语句
    map-underscore-to-camel-case: true #驼峰和下划线映射
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
    connection-timeout: 10000
    readTimeout: 10000
